# see: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # GitHub Actions (/.github/workflows/*.yml)
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '18:00'
      timezone: Asia/Tokyo
    cooldown:
      default-days: 5
    labels:
      - 'dependabot :robot:'
    commit-message:
      prefix: ci(gh-actions)
