name: Auto merge PRs on approval

on:
  workflow_call:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    name: Auto merge
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    runs-on: ubuntu-slim
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v3.1.1
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Check reviewer
        id: check_member
        run: |
          OWNER_TYPE=$(gh api users/$ORGANIZATION --jq '.type')
          if [ "$OWNER_TYPE" = "Organization" ]; then
            if gh api orgs/$ORGANIZATION/members/$REVIEWER --silent; then
              echo "is_member=true" >> $GITHUB_OUTPUT
            else
              echo "is_member=false" >> $GITHUB_OUTPUT
            fi
          else
            # For user repo, check the reviewer is the owner.
            if [ "$REVIEWER" = "$ORGANIZATION" ]; then
              echo "is_member=true" >> $GITHUB_OUTPUT
            else
              echo "is_member=false" >> $GITHUB_OUTPUT
            fi
          fi
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          REVIEWER: ${{ github.event.review.user.login }}
          ORGANIZATION: ${{ github.repository_owner }}

      - name: Send LGTM image
        if: steps.check_member.outputs.is_member == 'true'
        run: gh pr comment "$PR_URL" --body "![LGTM](${LGTM_URL})"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          LGTM_URL: https://raw.githubusercontent.com/ddradar/.github/refs/heads/main/assets/images/genbaneko.webp
      - name: Enable Auto merge
        if: steps.check_member.outputs.is_member == 'true'
        run: gh pr merge "$PR_URL" --auto --squash
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
